// Generated by Myco --emit-arduino
// Source: examples/arduino_blink.myco

void setup() {
  pinMode(13, OUTPUT);
}

void loop() {
  for (int i = 1010; i > 10; i -= 50) {
    digitalWrite(13, HIGH);
    delay(i);
    digitalWrite(13, LOW);
  }
}
