name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          
      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          # No external dependencies needed - Myco is self-contained
          
      - name: Build Myco
        run: |
          make clean
          make
          
      - name: Run test suite
        run: |
          # Add ulimit to increase stack size for Ubuntu
          ulimit -s unlimited || true
          # Run with timeout to prevent hanging
          timeout 60s ./bin/myco pass.myco || echo "Test suite failed with exit code $?"
          
      - name: Test individual libraries
        run: |
          echo 'print("Web framework test: " + web.type)' | ./bin/myco
          echo 'print("Database test: " + db.type)' | ./bin/myco
          echo 'print("JSON test: " + json.type)' | ./bin/myco
          echo 'print("Server test: " + server.type)' | ./bin/myco
          
      - name: Run performance benchmarks
        run: |
          if [ -f "benchmark/run_benchmarks.sh" ]; then
            chmod +x benchmark/run_benchmarks.sh
            ./benchmark/run_benchmarks.sh
          fi
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: myco-binary-${{ matrix.os }}
          path: |
            bin/myco
            benchmark/results/
          retention-days: 7
