name: Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm install -g @vuepress/cli
          
      - name: Build documentation
        run: |
          # Create basic documentation structure
          mkdir -p docs-site
          echo "# Myco Language Documentation" > docs-site/README.md
          echo "" >> docs-site/README.md
          echo "Welcome to the Myco programming language documentation." >> docs-site/README.md
          echo "" >> docs-site/README.md
          echo "## Quick Start" >> docs-site/README.md
          echo "" >> docs-site/README.md
          echo "1. Download the latest release from [GitHub Releases](https://github.com/IvyMycelia/Myco/releases)" >> docs-site/README.md
          echo "2. Make the binary executable: \`chmod +x myco\`" >> docs-site/README.md
          echo "3. Run your first program: \`echo 'print(\"Hello World\");' | ./myco\`" >> docs-site/README.md
          echo "" >> docs-site/README.md
          echo "## Features" >> docs-site/README.md
          echo "" >> docs-site/README.md
          echo "- Complete language implementation" >> docs-site/README.md
          echo "- Web framework with template engine" >> docs-site/README.md
          echo "- Database system" >> docs-site/README.md
          echo "- HTTP client with HTTPS support" >> docs-site/README.md
          echo "- JSON, Trees, Graphs libraries" >> docs-site/README.md
          echo "- 100% test success rate" >> docs-site/README.md
          
      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-site
          cname: mycolang.org
          force_orphan: true