name: Build Myco macOS Release

on:
  push:
    branches:
      - main
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          brew install libmicrohttpd curl readline zlib

      - name: Build Myco project
        run: |
          make clean
          make

      - name: Run test suite
        run: |
          ./bin/myco pass.myco

      - name: Test web framework
        run: |
          echo 'print("Web framework: " + web.type)' | ./bin/myco

      - name: Test database
        run: |
          echo 'print("Database: " + db.type)' | ./bin/myco

      - name: Create release archive
        run: |
          mkdir -p release
          cp bin/myco release/
          cp -r examples/ release/ 2>/dev/null || true
          cp -r docs/ release/ 2>/dev/null || true
          cp README.md release/
          tar -czf myco-macos-latest.tar.gz -C release .

      - name: Upload release assets
        uses: actions/upload-artifact@v4
        with:
          name: myco-macos-latest
          path: myco-macos-latest.tar.gz
