name: Performance Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 0'  # Weekly on Sunday

jobs:
  performance:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          brew install libmicrohttpd curl readline zlib
          
      - name: Build Myco with optimizations
        run: |
          make clean
          CFLAGS="-O3 -march=native" make
          
      - name: Run performance benchmarks
        run: |
          if [ -f "benchmark/run_benchmarks.sh" ]; then
            chmod +x benchmark/run_benchmarks.sh
            ./benchmark/run_benchmarks.sh
          else
            echo "No benchmark script found"
          fi
          
      - name: Test web framework performance
        run: |
          echo 'print("Testing web framework performance...")' | time ./bin/myco
          
      - name: Test database performance
        run: |
          echo 'print("Testing database performance...")' | time ./bin/myco
          
      - name: Memory usage test
        run: |
          echo 'print("Memory usage test")' | /usr/bin/time -v ./bin/myco 2>&1 || true
          
      - name: Upload performance results
        uses: actions/upload-artifact@v4
        with:
          name: performance-results-${{ github.run_number }}
          path: |
            benchmark/results/
            *.log
