name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      prerelease:
        description: 'Mark as prerelease'
        type: boolean
        default: false
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: read

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: []
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Determine version
        id: version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi
          
      - name: Download Ubuntu binary
        uses: actions/download-artifact@v4
        with:
          name: myco-binary-ubuntu-latest
          path: ./artifacts/ubuntu
          
      - name: Download macOS binary
        uses: actions/download-artifact@v4
        with:
          name: myco-binary-macos-latest
          path: ./artifacts/macos
          
      - name: Prepare release assets
        run: |
          mkdir -p ./release-assets
          
          # Ubuntu binary
          if [ -f "./artifacts/ubuntu/bin/myco" ]; then
            cp ./artifacts/ubuntu/bin/myco ./release-assets/myco-ubuntu-latest
            chmod +x ./release-assets/myco-ubuntu-latest
          fi
          
          # macOS binary
          if [ -f "./artifacts/macos/bin/myco" ]; then
            cp ./artifacts/macos/bin/myco ./release-assets/myco-macos-latest
            chmod +x ./release-assets/myco-macos-latest
          fi
          
          # Create checksums
          cd ./release-assets
          for file in *; do
            sha256sum "$file" > "$file.sha256"
          done
          
      - name: Generate release notes
        id: release_notes
        run: |
          cat > release_notes.md << EOF
          # Myco ${{ steps.version.outputs.version }}
          
          ## Downloads
          
          ### Ubuntu/Linux
          - \`myco-ubuntu-latest\` - Binary for Ubuntu/Linux
          - \`myco-ubuntu-latest.sha256\` - SHA256 checksum
          
          ### macOS
          - \`myco-macos-latest\` - Binary for macOS
          - \`myco-macos-latest.sha256\` - SHA256 checksum
          
          ## Installation
          
          1. Download the appropriate binary for your platform
          2. Make it executable: \`chmod +x myco-<platform>\`
          3. Move to your PATH: \`sudo mv myco-<platform> /usr/local/bin/myco\`
          4. Verify installation: \`myco --version\`
          
          ## Features
          
          - Complete Myco language implementation
          - 100% test success rate (323/323 tests passing)
          - Web framework with template engine
          - Database system with custom storage
          - HTTP client with HTTPS support
          - JSON, Trees, Graphs, and more libraries
          
          ## Performance
          
          - Optimized for speed and memory efficiency
          - Self-contained with no external dependencies
          - Cross-platform compatibility
          EOF
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Myco ${{ steps.version.outputs.version }}
          body_path: release_notes.md
          files: |
            ./release-assets/*
          prerelease: ${{ github.event.inputs.prerelease == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}