name: Stable Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
      prerelease:
        description: 'Is this a prerelease?'
        required: false
        default: false
        type: boolean

jobs:
  stable-release:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Validate version format
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [[ ! $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
            echo "Error: Version must be in format v1.0.0 or v1.0.0-beta"
            exit 1
          fi
          echo "Valid version: $VERSION"
          
      - name: Check if release exists
        id: check-release
        run: |
          if gh release view ${{ github.event.inputs.version }} >/dev/null 2>&1; then
            echo "Release ${{ github.event.inputs.version }} already exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Release ${{ github.event.inputs.version }} does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Install dependencies
        if: steps.check-release.outputs.exists == 'false'
        run: |
          brew install libmicrohttpd curl readline zlib gh
          
      - name: Build Myco
        if: steps.check-release.outputs.exists == 'false'
        run: |
          make clean
          make
          
      - name: Run comprehensive tests
        if: steps.check-release.outputs.exists == 'false'
        run: |
          ./bin/myco pass.myco
          echo 'print("Web framework: " + web.type)' | ./bin/myco
          echo 'print("Database: " + db.type)' | ./bin/myco
          
      - name: Run performance benchmarks
        if: steps.check-release.outputs.exists == 'false'
        run: |
          if [ -f "benchmark/run_benchmarks.sh" ]; then
            chmod +x benchmark/run_benchmarks.sh
            ./benchmark/run_benchmarks.sh
          fi
          
      - name: Create release archive
        if: steps.check-release.outputs.exists == 'false'
        run: |
          mkdir -p release
          cp bin/myco release/
          cp -r examples/ release/ 2>/dev/null || true
          cp -r docs/ release/ 2>/dev/null || true
          cp README.md release/
          cp LICENSE release/ 2>/dev/null || true
          cp -r benchmark/ release/ 2>/dev/null || true
          tar -czf myco-${{ github.event.inputs.version }}-macos.tar.gz -C release .
          
      - name: Create GitHub Release
        if: steps.check-release.outputs.exists == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Myco ${{ github.event.inputs.version }}
          files: myco-${{ github.event.inputs.version }}-macos.tar.gz
          generate_release_notes: true
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          body: |
            ## Myco ${{ github.event.inputs.version }}
            
            ### 🚀 What's New
            - **Complete Web Framework**: Full routing, middleware, templates, sessions
            - **Custom Database**: File-based storage with CRUD operations
            - **Template Engine**: Variable substitution, conditionals, loops
            - **Session Management**: Cookie-based tracking and cleanup
            - **All 323 Tests Passing**: Comprehensive test coverage
            - **Performance Optimized**: Built for speed and efficiency
            
            ### 📦 Installation
            1. Download the archive: `myco-${{ github.event.inputs.version }}-macos.tar.gz`
            2. Extract: `tar -xzf myco-${{ github.event.inputs.version }}-macos.tar.gz`
            3. Run: `./myco --help`
            
            ### ✨ Features
            - **Web Framework**: Express.js-like routing and middleware
            - **Database**: Custom file-based storage (no external dependencies)
            - **Templates**: Handlebars-like template engine
            - **Sessions**: Secure session management
            - **Performance**: Optimized C implementation
            - **Cross-platform**: macOS and Linux support
            
            ### 🔧 Development
            - **Source**: [GitHub Repository](https://github.com/${{ github.repository }})
            - **Documentation**: [Myco Docs](https://mycolang.org)
            - **Issues**: [Report Issues](https://github.com/${{ github.repository }}/issues)
            
            ### 📊 Performance
            - **Memory Efficient**: Optimized memory management
            - **Fast Execution**: Near-C performance
            - **Small Binary**: Minimal dependencies
            - **Cross-platform**: Works on macOS and Linux
